// js/products.js
// ByteCart product database — expanded for 3 categories:
// Categories: smartphones, laptops, home-appliances
// Each item contains: id, title, category, price (text), rating, desc, img, affiliateLink
// Affiliate links use your tag via search pages (safe, trackable).
// Later we can replace with PA-API direct ASIN links and official images.

const AMAZON_TAG = "theshadowgard-21";

const products = [
  // =========== SMARTPHONES (20 items) ===========
  { id: "sm-001", title: "Samsung Galaxy S23", category: "smartphones", price: "See on Amazon", rating: 4.6, desc: "Flagship Samsung phone with great camera and performance.", img: "https://via.placeholder.com/420x300?text=Galaxy+S23", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Samsung Galaxy S23")}&tag=${AMAZON_TAG}` },
  { id: "sm-002", title: "iPhone 14", category: "smartphones", price: "See on Amazon", rating: 4.6, desc: "Apple iPhone 14 with excellent camera and ecosystem.", img: "https://via.placeholder.com/420x300?text=iPhone+14", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("iPhone 14")}&tag=${AMAZON_TAG}` },
  { id: "sm-003", title: "OnePlus 11", category: "smartphones", price: "See on Amazon", rating: 4.5, desc: "High performance OnePlus flagship with fast charging.", img: "https://via.placeholder.com/420x300?text=OnePlus+11", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("OnePlus 11")}&tag=${AMAZON_TAG}` },
  { id: "sm-004", title: "Xiaomi 13", category: "smartphones", price: "See on Amazon", rating: 4.4, desc: "Xiaomi mid-high range phone with great value.", img: "https://via.placeholder.com/420x300?text=Xiaomi+13", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Xiaomi 13")}&tag=${AMAZON_TAG}` },
  { id: "sm-005", title: "Realme Narzo 70 Pro", category: "smartphones", price: "See on Amazon", rating: 4.2, desc: "Fast charging, good camera for budget segment.", img: "https://via.placeholder.com/420x300?text=Realme+Narzo+70+Pro", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Realme Narzo 70 Pro")}&tag=${AMAZON_TAG}` },
  { id: "sm-006", title: "iQOO Z7s 5G", category: "smartphones", price: "See on Amazon", rating: 4.1, desc: "Balanced specs for gamers and everyday users.", img: "https://via.placeholder.com/420x300?text=iQOO+Z7s+5G", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("iQOO Z7s 5G")}&tag=${AMAZON_TAG}` },
  { id: "sm-007", title: "Google Pixel 7a", category: "smartphones", price: "See on Amazon", rating: 4.4, desc: "Great camera software and clean Android experience.", img: "https://via.placeholder.com/420x300?text=Pixel+7a", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Google Pixel 7a")}&tag=${AMAZON_TAG}` },
  { id: "sm-008", title: "Motorola Edge 40", category: "smartphones", price: "See on Amazon", rating: 4.0, desc: "Sleek design and capable camera.", img: "https://via.placeholder.com/420x300?text=Motorola+Edge+40", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Motorola Edge 40")}&tag=${AMAZON_TAG}` },
  { id: "sm-009", title: "Vivo V29", category: "smartphones", price: "See on Amazon", rating: 4.1, desc: "Strong selfie camera & stylish looks.", img: "https://via.placeholder.com/420x300?text=Vivo+V29", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Vivo V29")}&tag=${AMAZON_TAG}` },
  { id: "sm-010", title: "OPPO Reno 10", category: "smartphones", price: "See on Amazon", rating: 4.0, desc: "Good value for mid-range users.", img: "https://via.placeholder.com/420x300?text=OPPO+Reno+10", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("OPPO Reno 10")}&tag=${AMAZON_TAG}` },
  { id: "sm-011", title: "Samsung Galaxy A54", category: "smartphones", price: "See on Amazon", rating: 4.2, desc: "Great battery life and smooth display.", img: "https://via.placeholder.com/420x300?text=Galaxy+A54", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Samsung Galaxy A54")}&tag=${AMAZON_TAG}` },
  { id: "sm-012", title: "Poco X6 Pro", category: "smartphones", price: "See on Amazon", rating: 4.1, desc: "High performance at a competitive price.", img: "https://via.placeholder.com/420x300?text=Poco+X6+Pro", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Poco X6 Pro")}&tag=${AMAZON_TAG}` },
  { id: "sm-013", title: "Samsung Galaxy Note 20 (refurb)", category: "smartphones", price: "See on Amazon", rating: 4.0, desc: "Classic power user device (check condition).", img: "https://via.placeholder.com/420x300?text=Galaxy+Note+20", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Samsung Galaxy Note 20")}&tag=${AMAZON_TAG}` },
  { id: "sm-014", title: "Infinix Note 30", category: "smartphones", price: "See on Amazon", rating: 3.9, desc: "Large display and good battery for price.", img: "https://via.placeholder.com/420x300?text=Infinix+Note+30", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Infinix Note 30")}&tag=${AMAZON_TAG}` },
  { id: "sm-015", title: "Nokia G21", category: "smartphones", price: "See on Amazon", rating: 3.8, desc: "Durable design and stock-like Android.", img: "https://via.placeholder.com/420x300?text=Nokia+G21", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Nokia G21")}&tag=${AMAZON_TAG}` },
  { id: "sm-016", title: "Tecno Camon 20", category: "smartphones", price: "See on Amazon", rating: 3.9, desc: "Camera focused budget phone.", img: "https://via.placeholder.com/420x300?text=Tecno+Camon+20", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Tecno Camon 20")}&tag=${AMAZON_TAG}` },
  { id: "sm-017", title: "Lava Agni 2", category: "smartphones", price: "See on Amazon", rating: 4.0, desc: "Made-for-India gaming phone.", img: "https://via.placeholder.com/420x300?text=Lava+Agni+2", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Lava Agni 2")}&tag=${AMAZON_TAG}` },
  { id: "sm-018", title: "Honor X9b", category: "smartphones", price: "See on Amazon", rating: 4.0, desc: "Balanced specs and modern design.", img: "https://via.placeholder.com/420x300?text=Honor+X9b", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Honor X9b")}&tag=${AMAZON_TAG}` },
  { id: "sm-019", title: "Asus Zenfone 9", category: "smartphones", price: "See on Amazon", rating: 4.3, desc: "Compact flagship with flagship chipset.", img: "https://via.placeholder.com/420x300?text=Asus+Zenfone+9", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Asus Zenfone 9")}&tag=${AMAZON_TAG}` },
  { id: "sm-020", title: "POCO F5", category: "smartphones", price: "See on Amazon", rating: 4.2, desc: "Great specs for gamers and power users.", img: "https://via.placeholder.com/420x300?text=POCO+F5", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("POCO F5")}&tag=${AMAZON_TAG}` },

  // =========== LAPTOPS (15 items) ===========
  { id: "lp-001", title: "HP Victus Gaming Laptop (Ryzen 5)", category: "laptops", price: "See on Amazon", rating: 4.2, desc: "Good starter gaming laptop with dedicated GPU.", img: "https://via.placeholder.com/420x300?text=HP+Victus+Ryzen+5", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("HP Victus Gaming Laptop Ryzen 5")}&tag=${AMAZON_TAG}` },
  { id: "lp-002", title: "Dell Inspiron 14 (Intel i5)", category: "laptops", price: "See on Amazon", rating: 4.1, desc: "Reliable daily driver for students and professionals.", img: "https://via.placeholder.com/420x300?text=Dell+Inspiron+14", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Dell Inspiron 14 i5")}&tag=${AMAZON_TAG}` },
  { id: "lp-003", title: "Lenovo IdeaPad Slim 3 (Ryzen 5)", category: "laptops", price: "See on Amazon", rating: 4.0, desc: "Lightweight laptop for productivity tasks.", img: "https://via.placeholder.com/420x300?text=Lenovo+IdeaPad+Slim+3", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Lenovo IdeaPad Slim 3 Ryzen 5")}&tag=${AMAZON_TAG}` },
  { id: "lp-004", title: "ASUS TUF Gaming A15", category: "laptops", price: "See on Amazon", rating: 4.3, desc: "Strong mid-range gaming laptop with good thermals.", img: "https://via.placeholder.com/420x300?text=ASUS+TUF+A15", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("ASUS TUF Gaming A15")}&tag=${AMAZON_TAG}` },
  { id: "lp-005", title: "Acer Aspire 5", category: "laptops", price: "See on Amazon", rating: 4.0, desc: "Affordable all-rounder with decent battery life.", img: "https://via.placeholder.com/420x300?text=Acer+Aspire+5", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Acer Aspire 5")}&tag=${AMAZON_TAG}` },
  { id: "lp-006", title: "Apple MacBook Air M2", category: "laptops", price: "See on Amazon", rating: 4.7, desc: "Excellent performance and battery life.", img: "https://via.placeholder.com/420x300?text=MacBook+Air+M2", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("MacBook Air M2")}&tag=${AMAZON_TAG}` },
  { id: "lp-007", title: "MSI Thin GF63", category: "laptops", price: "See on Amazon", rating: 4.1, desc: "Budget gaming laptop with decent GPU.", img: "https://via.placeholder.com/420x300?text=MSI+GF63", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("MSI GF63 Thin")}&tag=${AMAZON_TAG}` },
  { id: "lp-008", title: "HP Pavilion x360", category: "laptops", price: "See on Amazon", rating: 4.0, desc: "2-in-1 convertible for creative users.", img: "https://via.placeholder.com/420x300?text=HP+Pavilion+x360", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("HP Pavilion x360")}&tag=${AMAZON_TAG}` },
  { id: "lp-009", title: "Lenovo Legion 5", category: "laptops", price: "See on Amazon", rating: 4.4, desc: "Great gaming performance and build quality.", img: "https://via.placeholder.com/420x300?text=Lenovo+Legion+5", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Lenovo Legion 5")}&tag=${AMAZON_TAG}` },
  { id: "lp-010", title: "ASUS VivoBook 15", category: "laptops", price: "See on Amazon", rating: 4.0, desc: "Everyday laptop with solid specs for students.", img: "https://via.placeholder.com/420x300?text=ASUS+VivoBook+15", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("ASUS VivoBook 15")}&tag=${AMAZON_TAG}` },
  { id: "lp-011", title: "Dell G15 Gaming Laptop", category: "laptops", price: "See on Amazon", rating: 4.2, desc: "Reliable Dell gaming machine with dedicated GPU.", img: "https://via.placeholder.com/420x300?text=Dell+G15", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Dell G15 Gaming Laptop")}&tag=${AMAZON_TAG}` },
  { id: "lp-012", title: "HP 15s (Intel i3)", category: "laptops", price: "See on Amazon", rating: 3.9, desc: "Budget laptop for daily tasks.", img: "https://via.placeholder.com/420x300?text=HP+15s+i3", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("HP 15s i3")}&tag=${AMAZON_TAG}` },
  { id: "lp-013", title: "Apple MacBook Pro 14 (M1 Pro)", category: "laptops", price: "See on Amazon", rating: 4.8, desc: "Pro-level performance for creators.", img: "https://via.placeholder.com/420x300?text=MacBook+Pro+14", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("MacBook Pro 14 M1 Pro")}&tag=${AMAZON_TAG}` },
  { id: "lp-014", title: "Acer Nitro 5", category: "laptops", price: "See on Amazon", rating: 4.1, desc: "Budget gaming with good cooling.", img: "https://via.placeholder.com/420x300?text=Acer+Nitro+5", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Acer Nitro 5")}&tag=${AMAZON_TAG}` },
  { id: "lp-015", title: "Microsoft Surface Laptop Go", category: "laptops", price: "See on Amazon", rating: 4.0, desc: "Portable, premium-feel laptop for professionals.", img: "https://via.placeholder.com/420x300?text=Surface+Laptop+Go", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Surface Laptop Go")}&tag=${AMAZON_TAG}` },

  // =========== HOME APPLIANCES (15 items) ===========
  { id: "ha-001", title: "Philips Air Fryer Daily Collection 1.8L", category: "home-appliances", price: "See on Amazon", rating: 4.4, desc: "Healthy frying with less oil.", img: "https://via.placeholder.com/420x300?text=Philips+Air+Fryer", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Philips Air Fryer 1.8L")}&tag=${AMAZON_TAG}` },
  { id: "ha-002", title: "IFB 5 Star Fully Automatic Washing Machine 7kg", category: "home-appliances", price: "See on Amazon", rating: 4.3, desc: "Top-rated Indian washing machine.", img: "https://via.placeholder.com/420x300?text=IFB+Washing+Machine", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("IFB 7kg washing machine")}&tag=${AMAZON_TAG}` },
  { id: "ha-003", title: "Whirlpool 265 L 3 Star Refrigerator", category: "home-appliances", price: "See on Amazon", rating: 4.2, desc: "Reliable refrigerator with inverter compressor.", img: "https://via.placeholder.com/420x300?text=Whirlpool+Fridge", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Whirlpool 265 L refrigerator")}&tag=${AMAZON_TAG}` },
  { id: "ha-004", title: "Bajaj 750W Mixer Grinder", category: "home-appliances", price: "See on Amazon", rating: 4.0, desc: "Trusted brand for everyday kitchen use.", img: "https://via.placeholder.com/420x300?text=Bajaj+Mixer+Grinder", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Bajaj mixer grinder 750W")}&tag=${AMAZON_TAG}` },
  { id: "ha-005", title: "Mi Smart LED TV 4A 43 inch", category: "home-appliances", price: "See on Amazon", rating: 4.2, desc: "Smart TV with Android and streaming apps.", img: "https://via.placeholder.com/420x300?text=Mi+Smart+TV+43", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Mi Smart TV 43 inch")}&tag=${AMAZON_TAG}` },
  { id: "ha-006", title: "Eureka Forbes AquaSure RO Water Purifier", category: "home-appliances", price: "See on Amazon", rating: 4.1, desc: "RO + UV purification for safe drinking water.", img: "https://via.placeholder.com/420x300?text=Aquasure+RO", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Eureka Forbes AquaSure RO")}&tag=${AMAZON_TAG}` },
  { id: "ha-007", title: "Philips 1800W Hair Dryer", category: "home-appliances", price: "See on Amazon", rating: 4.0, desc: "Compact hair dryer with multiple heat settings.", img: "https://via.placeholder.com/420x300?text=Philips+Hair+Dryer", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Philips hair dryer 1800W")}&tag=${AMAZON_TAG}` },
  { id: "ha-008", title: "Prestige Induction Cooktop", category: "home-appliances", price: "See on Amazon", rating: 4.1, desc: "Fast heating induction cooktop.", img: "https://via.placeholder.com/420x300?text=Prestige+Induction+Cooktop", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Prestige induction cooktop")}&tag=${AMAZON_TAG}` },
  { id: "ha-009", title: "Philips Mixer Grinder 2 Litre", category: "home-appliances", price: "See on Amazon", rating: 4.0, desc: "Multi-purpose grinder for Indian kitchens.", img: "https://via.placeholder.com/420x300?text=Philips+Mixer", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Philips mixer grinder")}&tag=${AMAZON_TAG}` },
  { id: "ha-010", title: "Havells 1.5 Ton Split AC", category: "home-appliances", price: "See on Amazon", rating: 4.0, desc: "Reliable AC with energy-saving modes.", img: "https://via.placeholder.com/420x300?text=Havells+AC", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Havells 1.5 ton AC")}&tag=${AMAZON_TAG}` },
  { id: "ha-011", title: "Xiaomi Robot Vacuum Cleaner", category: "home-appliances", price: "See on Amazon", rating: 4.1, desc: "Smart cleaning with app control and schedules.", img: "https://via.placeholder.com/420x300?text=Xiaomi+Robot+Vacuum", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Xiaomi robot vacuum cleaner")}&tag=${AMAZON_TAG}` },
  { id: "ha-012", title: "Inalsa Air Fryer 3.2L", category: "home-appliances", price: "See on Amazon", rating: 4.0, desc: "Family-size air fryer for healthier cooking.", img: "https://via.placeholder.com/420x300?text=Inalsa+Air+Fryer", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Inalsa Air Fryer 3.2L")}&tag=${AMAZON_TAG}` },
  { id: "ha-013", title: "Kent Ultra UV Water Purifier", category: "home-appliances", price: "See on Amazon", rating: 4.1, desc: "Trusted brand for water purification.", img: "https://via.placeholder.com/420x300?text=Kent+Water+Purifier", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Kent water purifier")}&tag=${AMAZON_TAG}` },
  { id: "ha-014", title: "Philips Air Purifier 3000i", category: "home-appliances", price: "See on Amazon", rating: 4.3, desc: "High performance air purifier for large rooms.", img: "https://via.placeholder.com/420x300?text=Philips+Air+Purifier", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Philips air purifier 3000i")}&tag=${AMAZON_TAG}` },
  { id: "ha-015", title: "Preethi Mixer Grinder (3 jars)", category: "home-appliances", price: "See on Amazon", rating: 4.0, desc: "Popular Indian brand mixer grinder.", img: "https://via.placeholder.com/420x300?text=Preethi+Mixer+Grinder", affiliateLink: `https://www.amazon.in/s?k=${encodeURIComponent("Preethi mixer grinder 3 jars")}&tag=${AMAZON_TAG}` }
];

// Export for CommonJS if needed
if (typeof module !== 'undefined') module.exports = products;
